### ISSUE TITLE
Add AdminPanelProvider automatically

### ISSUE THREAD

**Issue by siemensikkema** [nodes-vapor/admin-panel-nodes-sso#13]
I discovered that the order in which the admin panel provider and the sso provider get added matters (sso comes last). How about adding the admin panel provider from inside the SSO one? That way only one provider has to be added in apps the problem of order of adding them is avoided.

@steffendsommer @BrettRToomey

**Comment by steffendsommer** [comment]
Fixed in https://github.com/nodes-vapor/admin-panel-nodes-sso/releases/tag/0.4.0 - the order of these two packages doesn't matter now.
