### ISSUE TITLE
Logging in and out is inconsistent

### ISSUE THREAD

**Issue by rasmusebbesen** [nodes-vapor/admin-panel-nodes-sso#3]
Logging in and out using SSO causes login to sporadically fail.

Upon failing no toast is shown. The user is left with the login form.

**Comment by Casperhr** [comment]
Please provide better error report @rasmusebbesen

**Comment by rasmusebbesen** [comment]
I will when I encounter the issue again. It has been 6 months ... perhaps it was fixed in the meantime

**Comment by steffendsommer** [comment]
Closing - please re-open if it happens again @rasmusebbesen
